azure:
  tag_id: "R31"
  subs: "9e15f7f5-cb3a-43d6-99c4-624c2faff15a"
  vn_rg: "RG-R31"
  vn_name: "VN-R31-07"
  vn_location: "southeastasia"
  vn_address: "10.7.0.0/16"
  vlan_mgmt: "10.7.0.0/24"
  vlan_ext: "10.7.10.0/24"
  vlan_int: "10.7.20.0/24"

bigip:
  vm_name: "vm-bigip-0701"
  vm_dnslabel: "r31-bigip-0701"
  ip_mgmt: "10.7.0.10"
  ip_ext: "10.7.10.10"
  ip_int: "10.7.20.10"
  vs_hackazon_01_ip: "10.7.10.11"
  vs_dvwa_01_ip: "10.7.10.12"
  vs_juiceshop_01_ip: "10.7.10.13"
  vs_hackazon_01_dnslabel: "r31-hackazon-0701"
  vs_dvwa_01_dnslabel: "r31-dvwa-0701"
  vs_juiceshop_01_dnslabel: "r31-juiceshop-0701"

ubuntu:
  vm_name: "vm-ubuntu-0701"
  vm_dnslabel: "r31-ubuntu-0701"
  ip_int: "10.7.20.100"

vault_password: "P@ssw0rd!1234"
